[package]

name = "maidsafe_client"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.github.io/maidsafe_client/latest/"
repository = "https://github.com/maidsafe/maidsafe_client"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
cbor = "*"
rustc-serialize = "*"
rust-crypto = "*"
lru_time_cache = "*"
maidsafe_types = "*"
routing = "*"
sodiumoxide = "0.0.4"
time = "0.1.25"
rand = "*"
self_encryption = "0.1.3"

[features]
USE_ACTUAL_ROUTING = []
